# Numpy
NumPy is an open source library available in Python that aids in mathematical, scientific, engineering, and data science programming. NumPy is an incredible library to perform mathematical and statistical operations. It works perfectly well for multi-dimensional arrays and matrices multiplication.


NumPy is a programming language that deals with multi-dimensional arrays and matrices. On top of the arrays and matrices, NumPy supports a large number of mathematical operations. In this part, we will review the essential functions that you need to know for the tutorial on 'Numpy.'


The library’s name is actually short for "Numeric Python" or "Numerical Python".

# Why NumPy ?
NumPy is memory efficiency, meaning it can handle the vast amount of data more accessible than any other library. Besides, NumPy is very convenient to work with, especially for matrix multiplication and reshaping. On top of that, NumPy is fast. In fact, Scikit learn(ML library) to use NumPy array to compute the matrix multiplication in the back end.

#### Import NumPy
Before start using numpy in your code, you have to import it

In [4]:
import numpy as np

Most commonly, numpy is imported with the alias 'np'.

# Numpy Array
NumPy arrays are a bit like Python lists, but still very much different at the same time. As the name kind of gives away, a NumPy array is a central data structure of the numpy library.

#### Create a NumPy Array
Simplest way to create an array in Numpy is to use Python List


In [6]:
myPythonList = [1,9,8,3]

To convert python list to a numpy array by using the object <b> np.array </b>.

In [7]:
numpy_array_from_list = np.array(myPythonList)

To display the contents of the list

In [8]:
print(numpy_array_from_list)

[1 9 8 3]


In [9]:
print(type(numpy_array_from_list))

<class 'numpy.ndarray'>


As we can see 'numpy_array_from_list' is now a numpy array.

In practice, there is no need to declare a Python List. The operation can be combined.

In [11]:
a  = np.array([1,9,8,3])
print(a)

[1 9 8 3]


#### Mathematical Operations on an Array
You could perform mathematical operations like additions, subtraction, division and multiplication on an array. The syntax is the array name followed by the operation (+.-,*,/) followed by the operand

In [12]:
print(numpy_array_from_list + 10)

[11 19 18 13]


This operation adds 10 to each element of the numpy array.

#### Shape of Array
You can check the shape of the array with the object shape preceded by the name of the array. In the same way, you can check the type with dtypes.

In [13]:
import numpy as np
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int32


An integer is a value without decimal. If you create an array with decimal, then the type will change to float.

In [14]:
#### Different type
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


#### 2-Dimension Array
You can add a dimension with a ","coma.
Note that it has to be within the bracket [].


In [15]:
### 2 dimension
c = np.array([(1,2,3),(4,5,6)])
print(c.shape)

(2, 3)


Similarly, higher dimensions arrays can also be created.

#### np.zeros and np.ones
You can create a matrix full of zeroes or ones using np.zeros and np.one commands respectively. It can be used when you initialized the weights during the machine learning training and other statistic tasks.

In [19]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [20]:
import numpy as np
print(np.ones((1,2,3)))

[[[1. 1. 1.]
  [1. 1. 1.]]]


#### Reshape Data
In some occasions, you need to reshape the data from wide to long. You can use the reshape function for this.


In [22]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)

[[1 2 3]
 [4 5 6]]


In [24]:
print(e.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


#### Flatten Data
When you need to deal with some advanced machine leaning algorithms like neural network, you need to flatten the array. You can use flatten().


In [25]:
print(e.flatten())

[1 2 3 4 5 6]


#### Random Numbers Generation
To generate random numbers for different distributions, we can use different random functions. 

In [38]:
## Generate random nmber from Gaussian distribution
standard_array = np.random.normal(0, 1, 10)
print(standard_array)

[-0.42961988 -1.92779115  0.55812445 -1.2276275   1.12331334  1.1420527
  0.0739283  -0.79199639  1.35543983 -0.3454129 ]


If plotted the distribution will be similar to following plot :
<img src = "Images/numpy_tut1.png">

In [42]:
## Generate random nmber from normal distribution
# first number denotes mean
# second number denotes standard deviation
# third number denotes size of the array
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[5.39297383 5.32995191 6.62958538 4.63684064 4.85598547 5.19460427
 4.77667286 5.05480573 5.47624144 4.58568941]


In [43]:
## Generate random nmber from uniform distribution
# first number denotes low
# second number denotes high
# third number denotes size of the array
uniform_array = np.random.uniform(0,1,10)
print(uniform_array)

[0.29985818 0.0153101  0.22345268 0.69973202 0.48216496 0.82479835
 0.43843043 0.59733783 0.92008554 0.38713758]


#### numpy.arange() 
Sometimes, you want to create values that are evenly spaced within a defined interval. For instance, you want to create values from 1 to 10; you can use numpy.arange() function

In [47]:
# first number denotes Start of interval
# second number denotes End of interval
# third number, if present, denotes spacing between values. Default step is 1
print(np.arange(1, 11))

[ 1  2  3  4  5  6  7  8  9 10]


If you want to change the step, you can add a third number in the parenthesis. It will change the step.

In [48]:
print(np.arange(1, 14, 4))

[ 1  5  9 13]


#### numpy.linspace()
Linspace gives evenly spaced samples.

In [49]:
# Start: Starting value of the sequence
# Stop: End value of the sequence
# Num: Number of samples to generate. Default is 50
# Endpoint: If True (default), stop is the last value. If False, stop value is not included.
np.linspace(1.0, 5.0, num=10)


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

#### Indexing and Slicing NumPy Arrays 
Slicing data is trivial with numpy. We will slice the matrice "e". Note that, in Python, you need to use the brackets to return the rows or columns

In [50]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)

[[1 2 3]
 [4 5 6]]


In [51]:
## First column
print('First row:', e[0])

First row: [1 2 3]


In [52]:
## Second col
print('Second row:', e[1])

Second row: [4 5 6]


The values before the comma stand for the rows. The value on the rights stands for the columns.
If you want to select a column, you need to add : before the column index.
: means you want all the rows from the selected column.

In [53]:
print('Second column:', e[:,1])

Second column: [2 5]


To return the first two values of the second row. You use : to select all columns up to the second

In [54]:
## Second Row, two values
print(e[1, :2])

[4 5]


#### NumPy Statistical Functions 
NumPy has quite a few useful statistical functions for finding minimum, maximum, percentile standard deviation and variance, etc from the given elements in the array.


In [55]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))


[5.15365594 4.61426302 4.42788193 6.16715473 4.27644805 4.42518478
 5.45294927 4.55114002 5.33408259 4.32080543]
4.276448045180074
6.167154725567189
4.872356574230242
4.582701516789127
0.5943516378347707
